///*
// * This C++ source file was generated by the Gradle 'init' task.
// */
//
//#include "kniitLibraryGradle.h"
//#include <cassert>
//
//int main() {
//    kniitLibraryGradle::Greeter greeter;
//    printf("Hello");
//    assert(greeter.greeting().compare("Hello, World!") == 0);
//    return 0;
//}
