name: Build and create development artifacts
on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows latest",
              os: windows-latest
          }
          - {
              name: "Linux latest",
              os: ubuntu-latest
          }
          - {
              name: "macOS latest",
              os: macos-latest
          }

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Install gcc multilib for linux
        if: runner.os == 'Linux'
        run: sudo apt-get install gcc-multilib g++-multilib
      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: clean prepareArtifactRelease
          gradle-version: 6.8.2
      - name: Create artifacts
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: createZipArtifacts
          gradle-version: 6.8.2
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: 'build/artifacts/*'