name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.0
      with:
        cmake-version: '3.16.5'
        github-api-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Use cmake
      run: cmake ./CMakeLists.txt
    - name: Display the directory 
      run: ls
      shell: bash